"""Synthetic panel generator and labeller (Rev 2 §15.4 - §15.5).

Two frames come out of here and they are never conflated:

* ``demand_panel``  -- ``sku_id, period, demand_observed, demand_true, stockout_flag,
  panel``. The §27 contract. This is all the policy ever sees.
* ``ground_truth``  -- the §27 ``GROUND_TRUTH_COLUMNS`` contract: one row per
  (sku, period) carrying ``true_cause``, ``cause_active``, ``injection_param``,
  ``detection_budget_flag``, ``c2_variant``, ``panel_gap``. Unreachable by the policy.
* ``generator_params`` -- one row per SKU: the generator's own state (``p``, ``k``,
  ``mu_z``, the solved ``gamma``, the C7 safety scale), the burn-in cell, the
  full-series ADI/CV^2 (**EVALUATION ONLY**, §27), and every constraint's audit flag.

**Why the ground truth is auditable rather than asserted.** The generator writes down
the parameters it used, so a label can be regenerated and checked. Revision 1's
labeller applied ``inject_C0`` to C2 and C7 series and then labelled them ``C2`` and
``C7`` anyway -- 400 series of fake ground truth that would have made the attribution
result meaningless. ``INJECTORS`` below has an entry for every cause, and
``assert_injector_coverage`` fails loudly if one is ever missing again.

**Determinism (§15.6).** Every series draws from a generator seeded by
``SeedSequence(seed, spawn_key=(panel_id, index))``, so a series' values do not depend
on how many other series were generated before it. Adding a panel does not move
another panel's numbers.
"""

from __future__ import annotations

import json

import numpy as np
import pandas as pd

from .generator import (
    CELLS,
    adi,
    burn_in_stats,
    cv_squared,
    draw_statics,
    get_cell_params,
    sb_cell,
)
from .injections import INJECTORS, inject_C0

__all__ = [
    "generate_panel",
    "generate_labelled_panel",
    "assert_injector_coverage",
    "PANEL_IDS",
    "SINGLE_CAUSES",
]

#: Every cause that must have its own injector. C2b is a VARIANT of C2, generated as
#: its own panel (constraint 5) so the detector's behaviour on each can be reported
#: separately; it is never folded into the seven-cause macro-F1.
SINGLE_CAUSES = ("C1", "C2", "C3", "C4", "C5", "C6", "C7")

#: Stable spawn keys, so a panel's draws never shift when another panel changes size.
PANEL_IDS = {"control": 0, "single": 1, "mixture": 2, "c2b": 3}

DEFAULT_T = 200
DEFAULT_TAU = 120
DEFAULT_BURN_IN = 24

#: C4's evidence floor, mirroring ``monitor.min_evidence.c4_nonzero`` and
#: ``detection``'s W_sz. Used only to FLAG constraint 9; never to relax it.
C4_W_SZ = 24
C4_MIN_EVIDENCE = 8


def assert_injector_coverage() -> None:
    """Fail loudly if any labelled cause has no injector.

    This is the check that would have caught Revision 1's C2/C7 fallback: those two
    causes were labelled while being generated by ``inject_C0``.
    """
    missing = [c for c in (*SINGLE_CAUSES, "C0", "ambiguous") if c not in INJECTORS]
    if missing:
        raise RuntimeError(
            f"labelled causes with no injector: {missing}. Generating these as C0 and "
            "labelling them by cause produces fake ground truth (Rev 2 §15.5)."
        )


def _sku_rng(seed: int, panel: str, index: int) -> np.random.Generator:
    """A per-series generator that does not depend on generation order (§15.6)."""
    return np.random.default_rng(
        np.random.SeedSequence(seed, spawn_key=(PANEL_IDS[panel], int(index)))
    )


def _series(
    cause: str,
    panel: str,
    index: int,
    T: int,
    tau: int,
    burn_in: int,
    rng: np.random.Generator,
) -> tuple[np.ndarray, dict, dict]:
    """Generate one labelled series. Returns ``(y, ground_truth_row, param_row)``."""
    cell = str(rng.choice(CELLS))
    # The static attributes are drawn from their OWN child stream, not the series'
    # stream. Drawing them inline would consume two to three draws before the parameter
    # draw and shift every cell, p, k and mu_z in the panel -- the panel's cell shares
    # moved from 0.146 to 0.136 for `high_highdisp` the moment statics were added, which
    # is a coupling with no meaning behind it. `spawn` gives each block of randomness its
    # own stream, so neither can move the other.
    statics = draw_statics(rng.spawn(1)[0])
    p, k, mu_z = get_cell_params(cell, rng)
    injector = INJECTORS[cause]
    y, delta, z, params = injector(T, tau, p, k, mu_z, rng)

    adi_init, cv2_init = burn_in_stats(y, burn_in)
    a_full, c_full = adi(y), cv_squared(y)

    # Constraint 9 -- C4's evidence budget, measured on the post-injection window that
    # the detector will actually have at the end of the panel.
    n_nz_post = int(np.count_nonzero(y[-C4_W_SZ:]))
    c4_ok = n_nz_post >= C4_MIN_EVIDENCE

    # Constraint 1 -- both shapes must lie on the same side of CV2_STAR.
    cv2_before, cv2_after = params.get("cv2_before"), params.get("cv2_after")
    if cv2_before is None or cv2_after is None:
        band_ok = True          # not a C4 series; the constraint does not apply
    else:
        band_ok = (float(cv2_before) - 0.49) * (float(cv2_after) - 0.49) > 0

    # Constraint 3 -- C5's detectability budget. If the injector could not scale the
    # step up to clear it (only reachable on the occurrence branch, where the required
    # step grows as 1/p while p is bounded), the SKU is FLAGGED, not dropped and not
    # silently accepted. Non-C5 series are not subject to this budget.
    c5_cleared = bool(params.get("budget_cleared", True)) if cause == "C5" else True

    # The §27 ``detection_budget_flag`` is a single column, so it carries the
    # conjunction: True means "this SKU's injected change cleared every budget that
    # applies to it, so it is evaluable at the stated window". A False here is the
    # spec's own escape clause for constraints 3 and 9 -- a reported exclusion, never
    # a silent one.
    budget_flag = bool(c4_ok and c5_cleared)

    gt = {
        "true_cause": cause,
        "cause_active": int(tau),
        "injection_param": json.dumps(params, sort_keys=True, default=str),
        "detection_budget_flag": budget_flag,
        "c2_variant": (
            "direct" if cause == "C2" else ("c2b" if cause == "C2b" else "-")
        ),
        "panel_gap": int(params.get("gap", 0)),
    }
    param = {
        "panel": panel,
        "true_cause": cause,
        "p": float(p),
        "k": float(k),
        "mu_z": float(mu_z),
        "sb_cell_init": sb_cell(adi_init, cv2_init),
        "sb_cell_sampled": cell,
        "adi_init": float(adi_init),
        "cv2_init": float(cv2_init),
        # EVALUATION ONLY (Rev 2 §27): full-series ADI/CV^2 would leak the post-regime
        # answer. Present so the report can describe the panel; never a policy input.
        "adi_full": float(a_full),
        "cv_squared_full": float(c_full) if np.isfinite(c_full) else float("nan"),
        "sb_cell_full": sb_cell(a_full, c_full),
        "n_nonzero": int(np.count_nonzero(y > 0)),
        "n_nonzero_post_W_sz": n_nz_post,
        "c4_budget_met": bool(c4_ok),
        "c4_band_ok": bool(band_ok),
        "c5_budget_cleared": c5_cleared,
        "c5_target": params.get("target"),
        "c5_occurrence_feasible": params.get("occurrence_feasible"),
        "c1_p_shift": params.get("p_shift"),
        "c1_k_shift": params.get("k_shift"),
        # The pooled LightGBM's static features. Drawn before the series, so they carry
        # no information about the post-injection regime.
        **statics,
        "detection_budget_flag": budget_flag,
        "cv2_before": cv2_before,
        "cv2_after": cv2_after,
        "gamma": params.get("gamma"),
        "c2_calib_window": params.get("calib_window"),
        "coverage_achieved": params.get("coverage_achieved"),
        "coverage_gap": params.get("coverage_gap"),
        "gap_clears_with_margin": params.get("gap_clears_with_margin"),
        "safety_scale": params.get("safety_scale"),
        "c7_fit_on": params.get("fit_on"),
        "demand_touched": bool(params.get("demand_touched", False)),
        "delta_frac_pre": float(delta[:tau].mean()),
        "delta_frac_post": float(delta[tau:].mean()),
    }
    return y, gt, param


def generate_labelled_panel(
    seed: int = 42,
    *,
    T: int = DEFAULT_T,
    tau_inj: int = DEFAULT_TAU,
    burn_in: int = DEFAULT_BURN_IN,
    n_per_cause: int = 200,
    n_control: int = 200,
    n_mixture: int = 200,
    n_c2b: int = 200,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Build the full labelled panel.

    Panel sizes follow §15.4: ``7 x n_per_cause`` single-cause (1,400) + ``n_control``
    (200) + ``n_mixture`` (200) = **1,800**. **Plus a C2b panel**, which §15.4's table
    predates: constraint 5 requires both C2 and C2b panels to exist, so the panel total
    is 1,800 + 200 = **2,000**. Recorded rather than absorbed silently.
    """
    assert_injector_coverage()

    demand_rows: list[dict] = []
    gt_rows: list[dict] = []
    param_rows: list[dict] = []

    plan: list[tuple[str, str, int]] = []
    for i in range(n_control):
        plan.append(("C0", "control", i))
    for cause in SINGLE_CAUSES:
        for i in range(n_per_cause):
            plan.append((cause, "single", i))
    for i in range(n_mixture):
        plan.append(("ambiguous", "mixture", i))
    for i in range(n_c2b):
        plan.append(("C2b", "c2b", i))

    for cause, panel, index in plan:
        rng = _sku_rng(seed, panel, index)
        sku_id = f"{panel}:{cause}:{index:04d}"
        y, gt, param = _series(cause, panel, index, T, tau_inj, burn_in, rng)

        for t in range(T):
            demand_rows.append(
                {
                    "sku_id": sku_id,
                    "period": t,
                    # No censoring at the panel level: stock-outs are the SIMULATOR's
                    # counterfactual cost layer, applied at run time (§15.6).
                    "demand_observed": float(y[t]),
                    "demand_true": float(y[t]),
                    "stockout_flag": False,
                    "panel": panel,
                }
            )
            gt_rows.append(
                {
                    "sku_id": sku_id,
                    "period": t,
                    "true_cause": gt["true_cause"],
                    "cause_active": bool(t >= gt["cause_active"]),
                    "injection_param": gt["injection_param"],
                    "detection_budget_flag": gt["detection_budget_flag"],
                    "c2_variant": gt["c2_variant"],
                    "panel_gap": gt["panel_gap"],
                }
            )
        param_rows.append({"sku_id": sku_id, **param})

    demand = pd.DataFrame(demand_rows)
    ground_truth = pd.DataFrame(gt_rows)
    generator_params = pd.DataFrame(param_rows)
    return demand, ground_truth, generator_params


def generate_panel(seed: int, n_series: int = 1800) -> pd.DataFrame:
    """Backwards-compatible long frame: demand plus its per-period labels.

    Kept for gates 4.1 (determinism) and 4.2 (class counts), which read
    ``sb_cell_init`` at ``period == 0``. New work should use
    :func:`generate_labelled_panel`, which splits the demand from the ground truth so
    the policy can be handed one without the other.
    """
    assert_injector_coverage()
    # Scale the panel sizes to the requested total, keeping §15.4's proportions.
    per = max(1, n_series // 9)
    demand, gt, params = generate_labelled_panel(
        seed,
        n_per_cause=per,
        n_control=per,
        n_mixture=per,
        n_c2b=0,
    )
    df = demand.merge(gt, on=["sku_id", "period"], how="left")
    df = df.merge(
        params[["sku_id", "sb_cell_init", "adi_init", "cv2_init"]],
        on="sku_id",
        how="left",
    )
    df["cause_active"] = df["cause_active"].astype(int)
    return df
