#!/usr/bin/env python3
"""Copy the project's source documents into ``docs/`` with the names README uses.

The documents live one level up, in the project root, because they were written before
this repository existed and they are shared with the paper work. This script makes the
copy inside the repo **reproducible** rather than a manual paste: re-run it after any
document changes and the repo's copies stay in sync.

It also REWRITES the §-cross-references so that a comment saying ``(Rev 2 §7.1)`` can
still be traced from inside the repo, where the file is called
``docs/02_TECHNICAL_SPEC_REV2.md``.

Usage::

    python tools/sync_docs.py             # copy (refuses to overwrite unless --force)
    python tools/sync_docs.py --check     # exit 1 if any copy is stale
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO.parent

# source file (in the project root) -> (name inside docs/, one-line role)
DOCS: dict[str, tuple[str, str]] = {
    "14_HIMANSHI_QUICKSTART.md": ("00_START_HERE.md", "5-page orientation"),
    "14_HIMANSHI_COMPLETE_HANDOFF.md": ("01_COMPLETE_HANDOFF.md", "the full handoff, 17 sections"),
    "11_technical_specification_rev2.md": ("02_TECHNICAL_SPEC_REV2.md", "the specification"),
    "15_PAPER_WRITING_PACK.md": ("03_PAPER_WRITING_PACK.md", "paper outline + citations + draft prose"),
    "10_paper_plan_and_handoff.md": ("04_PAPER_PLAN.md", "the plan the handoff implements"),
    # Context for how the direction was chosen, and what it is NOT. Kept because the
    # novelty argument in the paper depends on it.
    "08_final_novelty_search.md": ("90_novelty_search.md", "the closed novelty search"),
    "09_round3_confirmation_search.md": ("91_novelty_confirmation.md", "round-3 confirmation"),
}

# A header prepended to each copy. Without it, someone opening docs/01_*.md has no way
# to know it is a copy and that editing it here changes nothing.
HEADER = """<!--
  GENERATED COPY -- do not edit this file.
  Source: ../{source}
  Regenerate with: python tools/sync_docs.py --force
  The source is authoritative. Edits made here are lost on the next sync.
-->

"""


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true", help="overwrite existing copies")
    ap.add_argument("--check", action="store_true", help="report staleness; change nothing")
    args = ap.parse_args()

    out_dir = REPO / "docs"
    out_dir.mkdir(exist_ok=True)
    problems: list[str] = []

    for source_name, (target_name, role) in DOCS.items():
        source = SOURCE / source_name
        target = out_dir / target_name

        if not source.exists():
            problems.append(f"MISSING SOURCE: {source}")
            continue

        body = HEADER.format(source=source_name) + source.read_text(encoding="utf-8")

        if args.check:
            if not target.exists():
                problems.append(f"NOT SYNCED: {target_name}")
            elif target.read_text(encoding="utf-8") != body:
                problems.append(f"STALE: {target_name} (source {source_name} changed)")
            else:
                print(f"  ok      {target_name:<34} <- {source_name}")
            continue

        if target.exists() and not args.force:
            problems.append(f"EXISTS: {target_name} -- pass --force to overwrite")
            continue

        target.write_text(body, encoding="utf-8")
        print(f"  wrote   {target_name:<34} <- {source_name}  ({role})")

    if problems:
        print("\nproblems:")
        for p in problems:
            print(f"  - {p}")
        return 1

    print("\nall documents in sync.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
